# Routes configuration file

/:
  method: get
  to: home:index


/index:
    method: get
    to: book:index

/create:
    method: get
    to: book:create

/store:
    method: post
    to: book:store

/edit/{id}:
  method: get
  to: book:edit

/details/{id}:
  method: get
  to: book:details

/update/{id}:
  method: post
  to: book:update

/delete/{id}:
  method: post
  to: book:delete

